### ISSUE TITLE
Min/max time is treated as if it spans midnight-midnight

### ISSUE THREAD

**Issue by dracos** [transitland/transitland-processing-animation#2]
You can see the problem with e.g.
`python transitflow.py --name="CrossCountry" --operator o-gc-crosscountry`
The first train is at 04:44, last train ends at 00:07. 

The start/end frames of the trips are calculated by treating minDate-maxDate as mapping to all the frames. But the counts are treated as one count per frame, starting at midnight. This means that the displayed lines/counts do not match the display of the trips.

![image](https://user-images.githubusercontent.com/154364/29968867-83d2b48a-8f15-11e7-8151-cfeb779c0678.png)

I have worked around this by editing the csv files to match up the counts to the right times.

**Comment by willgeary** [comment]
Thanks! I'm glad you worked around it by editing the csv files manually. Will look into it.

**Comment by willgeary** [comment]
Fixed. count_vehicles_on_screen() no longer assumes a 24 hour window, but finds the true min and max dates from the dataset. @dracos

**Comment by dracos** [comment]
Thanks :)
