### ISSUE TITLE
Operator download failure

### ISSUE THREAD

**Issue by Shuake** [transitland/transitland-processing-animation#3]
Hi,
I haven't been able to download for operator [Champaign-Urbana Mass Transit District](https://transit.land/feed-registry/operators/o-dp1h-champaignurbanamasstransitdistrict) . Changing date didn't help ("service_start_date":"2017-08-13","service_end_date":"2017-12-23"). 
This is a really nice tool. Would appreciate if someone could take a look!

Thanks!
Shuake

failed:
u's-dp1k179mzs-floridaandjamescherry<fljascher~3'
0 operators successfully downloaded.
1 operators failed.
failed operators: ['o-dp1h-champaignurbanamasstransitdistrict']
Concatenating individual operator outputs.
Traceback (most recent call last):
  File "transitflow.py", line 379, in <module>
    df = concatenate_csvs("sketches/{}/{}/data/indiv_operators".format(OUTPUT_NA
ME, DATE))
  File "transitflow.py", line 158, in concatenate_csvs
    concatenated_df   = pd.concat(df_from_each_file, ignore_index=True)
  File "C:\ProgramData\Anaconda2\lib\site-packages\pandas\core\reshape\concat.py
", line 206, in concat
    copy=copy)
  File "C:\ProgramData\Anaconda2\lib\site-packages\pandas\core\reshape\concat.py
", line 239, in __init__
    raise ValueError('No objects to concatenate')
ValueError: No objects to concatenate

**Comment by willgeary** [comment]
Hi, this problem is now fixed, @Shuake !

It works for me: 

`python transitflow.py --name=champaign_urbana --operator=o-dp1h-champaignurbanamasstransitdistrict`

[Champaign-Urbana Mass Transit District](https://i.imgur.com/N1DSmb3.png)

**Comment by mmorley0395** [comment]
I had the same issue, ran the code you suggested and the code ran successfully but for some reason the sketches don't save into the sketch folder, there's just an indiv_operators folder. Sorry I'm new to Python and much of this so forgive me if this is the wrong way/place to comment on these sort of things!
