### ISSUE TITLE
SyntaxError: invalid syntax with 'print len'

### ISSUE THREAD

**Issue by AnthonyLovesBikes** [transitland/transitland-processing-animation#5]
Hello, I have the following error when I run the tool as shown below - I am using Python 3.6 not sure if this is the issue? Thanks for any help, I am fairly new but very keen to try and make this work! 

C:\Users\Anthony\Desktop\transitland-processing-animation-master\transitflow>python transitflow.py --name=GO --operator=o-dpz-gotransit
  File "transitflow.py", line 37
    print len(lookup_vehicle_types.keys()), "routes found.\n"
            ^
SyntaxError: invalid syntax

**Comment by willgeary** [comment]
Thanks -- yes, this is a python 3 vs python 2 issue. Python 2 print commands look like `print this` vs Python 3 print commands, which look like `print(this)`. You could fix this to work with Python 3 quite easily. More info here: http://sebastianraschka.com/Articles/2014_python_2_3_key_diff.html

**Comment by AnthonyLovesBikes** [comment]
Thanks, I ran it with Python 2.7 and it worked perfectly! Result is here: https://youtu.be/g5vcUoIjTRA
Thanks!

**Comment by willgeary** [comment]
Looks great!

**Comment by Mr-Lawrence-521** [comment]
Sorry to interrupt，I am facing a similar problem：
File "/public/home/guolang/software/MatchAnnot-master/matchAnnot.py", line 92
    print '\nisoform:  %-16s' % (clusterName)
          ^
SyntaxError: invalid syntax
Could anyone help to solve the problem？ Thanks very much！
